---
- name: ubuntu configuration
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  
- name: "Configure resolv.conf"
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "0644"
  become: true
